
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:06:15.728-04:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "WS-BaseNotificationService",
                      portName = "NotificationProducerPort",
                      targetNamespace = "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/service",
                      wsdlLocation = "/schema/org/cagrid/wsrf/notification/WS-BaseN_service.wsdl",
                      endpointInterface = "org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.NotificationProducer")
                      
public class NotificationProducerImpl implements NotificationProducer {

    private static final Logger LOG = Logger.getLogger(NotificationProducerImpl.class.getName());

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.NotificationProducer#getCurrentMessage(org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.GetCurrentMessage  getCurrentMessageRequest )*
     */
    public org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.GetCurrentMessageResponse getCurrentMessage(org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.GetCurrentMessage getCurrentMessageRequest) throws ResourceUnknownFault , InvalidTopicExpressionFault , NoCurrentMessageOnTopicFault , TopicNotSupportedFault    { 
        LOG.info("Executing operation getCurrentMessage");
        System.out.println(getCurrentMessageRequest);
        try {
            org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.GetCurrentMessageResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new InvalidTopicExpressionFault("InvalidTopicExpressionFault...");
        //throw new NoCurrentMessageOnTopicFault("NoCurrentMessageOnTopicFault...");
        //throw new TopicNotSupportedFault("TopicNotSupportedFault...");
    }

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.NotificationProducer#getResourceProperty(javax.xml.namespace.QName  getResourcePropertyRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName getResourcePropertyRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getResourceProperty");
        System.out.println(getResourcePropertyRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.NotificationProducer#subscribe(org.xmlsoap.schemas.ws._2004._03.addressing.EndpointReferenceType  consumerReference ,)org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.TopicExpressionType  topicExpression ,)java.lang.Boolean  useNotify ,)org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryExpressionType  precondition ,)org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryExpressionType  selector ,)java.lang.Object  subscriptionPolicy ,)java.util.Calendar  initialTerminationTime )*
     */
    public org.xmlsoap.schemas.ws._2004._03.addressing.EndpointReferenceType subscribe(org.xmlsoap.schemas.ws._2004._03.addressing.EndpointReferenceType consumerReference,org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.TopicExpressionType topicExpression,java.lang.Boolean useNotify,org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryExpressionType precondition,org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.QueryExpressionType selector,java.lang.Object subscriptionPolicy,java.util.Calendar initialTerminationTime) throws ResourceUnknownFault , SubscribeCreationFailedFault , InvalidTopicExpressionFault , TopicPathDialectUnknownFault , TopicNotSupportedFault    { 
        LOG.info("Executing operation subscribe");
        System.out.println(consumerReference);
        System.out.println(topicExpression);
        System.out.println(useNotify);
        System.out.println(precondition);
        System.out.println(selector);
        System.out.println(subscriptionPolicy);
        System.out.println(initialTerminationTime);
        try {
            org.xmlsoap.schemas.ws._2004._03.addressing.EndpointReferenceType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new SubscribeCreationFailedFault("SubscribeCreationFailedFault...");
        //throw new InvalidTopicExpressionFault("InvalidTopicExpressionFault...");
        //throw new TopicPathDialectUnknownFault("TopicPathDialectUnknownFault...");
        //throw new TopicNotSupportedFault("TopicNotSupportedFault...");
    }

}
