
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:06:15.765-04:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "WS-BaseNotificationService",
                      portName = "NotificationConsumerPort",
                      targetNamespace = "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/service",
                      wsdlLocation = "/schema/org/cagrid/wsrf/notification/WS-BaseN_service.wsdl",
                      endpointInterface = "org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.NotificationConsumer")
                      
public class NotificationConsumerImpl implements NotificationConsumer {

    private static final Logger LOG = Logger.getLogger(NotificationConsumerImpl.class.getName());

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.NotificationConsumer#notify(java.util.List<org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.NotificationMessageHolderType>  notificationMessage )*
     */
    public void notify(java.util.List<org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.NotificationMessageHolderType> notificationMessage) { 
        LOG.info("Executing operation notify");
        System.out.println(notificationMessage);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
