
package org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:06:15.601-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "ResourceUnknownFault", targetNamespace = "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.xsd")
public class ResourceUnknownFault extends Exception {
    
    private org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ResourceUnknownFaultType resourceUnknownFault;

    public ResourceUnknownFault() {
        super();
    }
    
    public ResourceUnknownFault(String message) {
        super(message);
    }
    
    public ResourceUnknownFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceUnknownFault(String message, org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ResourceUnknownFaultType resourceUnknownFault) {
        super(message);
        this.resourceUnknownFault = resourceUnknownFault;
    }

    public ResourceUnknownFault(String message, org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ResourceUnknownFaultType resourceUnknownFault, Throwable cause) {
        super(message, cause);
        this.resourceUnknownFault = resourceUnknownFault;
    }

    public org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01.ResourceUnknownFaultType getFaultInfo() {
        return this.resourceUnknownFault;
    }
}
