
package org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.service.WSBaseNotificationService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:06:15.575-04:00
 * Generated source version: 2.6.3
 * 
 */
public final class SubscriptionManager_SubscriptionManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/service", "WS-BaseNotificationService");

    private SubscriptionManager_SubscriptionManagerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSBaseNotificationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSBaseNotificationService ss = new WSBaseNotificationService(wsdlURL, SERVICE_NAME);
        SubscriptionManager port = ss.getSubscriptionManagerPort();  
        
        {
        System.out.println("Invoking resumeSubscription...");
        try {
            port.resumeSubscription();

        } catch (ResumeFailedFault e) { 
            System.out.println("Expected exception: ResumeFailedFault has occurred.");
            System.out.println(e.toString());
        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setTerminationTime...");
        java.util.Calendar _setTerminationTime_requestedTerminationTime = null;
        javax.xml.ws.Holder<java.util.Calendar> _setTerminationTime_newTerminationTime = new javax.xml.ws.Holder<java.util.Calendar>();
        javax.xml.ws.Holder<java.util.Calendar> _setTerminationTime_currentTime = new javax.xml.ws.Holder<java.util.Calendar>();
        try {
            port.setTerminationTime(_setTerminationTime_requestedTerminationTime, _setTerminationTime_newTerminationTime, _setTerminationTime_currentTime);

            System.out.println("setTerminationTime._setTerminationTime_newTerminationTime=" + _setTerminationTime_newTerminationTime.value);
            System.out.println("setTerminationTime._setTerminationTime_currentTime=" + _setTerminationTime_currentTime.value);
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.TerminationTimeChangeRejectedFault e) { 
            System.out.println("Expected exception: TerminationTimeChangeRejectedFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.UnableToSetTerminationTimeFault e) { 
            System.out.println("Expected exception: UnableToSetTerminationTimeFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking destroy...");
        try {
            port.destroy();

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceNotDestroyedFault e) { 
            System.out.println("Expected exception: ResourceNotDestroyedFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getResourceProperty...");
        javax.xml.namespace.QName _getResourceProperty_getResourcePropertyRequest = new javax.xml.namespace.QName("", "");
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _getResourceProperty__return = port.getResourceProperty(_getResourceProperty_getResourcePropertyRequest);
            System.out.println("getResourceProperty.result=" + _getResourceProperty__return);

        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault e) { 
            System.out.println("Expected exception: InvalidResourcePropertyQNameFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking pauseSubscription...");
        try {
            port.pauseSubscription();

        } catch (ResourceUnknownFault e) { 
            System.out.println("Expected exception: ResourceUnknownFault has occurred.");
            System.out.println(e.toString());
        } catch (PauseFailedFault e) { 
            System.out.println("Expected exception: PauseFailedFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
