
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:06:15.750-04:00
 * Generated source version: 2.6.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "WS-BaseNotificationService",
                      portName = "SubscriptionManagerPort",
                      targetNamespace = "http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/service",
                      wsdlLocation = "/schema/org/cagrid/wsrf/notification/WS-BaseN_service.wsdl",
                      endpointInterface = "org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.SubscriptionManager")
                      
public class SubscriptionManagerImpl implements SubscriptionManager {

    private static final Logger LOG = Logger.getLogger(SubscriptionManagerImpl.class.getName());

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.SubscriptionManager#resumeSubscription(*
     */
    public void resumeSubscription() throws ResumeFailedFault , ResourceUnknownFault    { 
        LOG.info("Executing operation resumeSubscription");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResumeFailedFault("ResumeFailedFault...");
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
    }

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.SubscriptionManager#setTerminationTime(java.util.Calendar  requestedTerminationTime ,)java.util.Calendar  newTerminationTime ,)java.util.Calendar  currentTime )*
     */
    public void setTerminationTime(java.util.Calendar requestedTerminationTime,javax.xml.ws.Holder<java.util.Calendar> newTerminationTime,javax.xml.ws.Holder<java.util.Calendar> currentTime) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.TerminationTimeChangeRejectedFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.UnableToSetTerminationTimeFault    { 
        LOG.info("Executing operation setTerminationTime");
        System.out.println(requestedTerminationTime);
        try {
            java.util.Calendar newTerminationTimeValue = null;
            newTerminationTime.value = newTerminationTimeValue;
            java.util.Calendar currentTimeValue = null;
            currentTime.value = currentTimeValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.TerminationTimeChangeRejectedFault("TerminationTimeChangeRejectedFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.UnableToSetTerminationTimeFault("UnableToSetTerminationTimeFault...");
    }

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.SubscriptionManager#destroy(*
     */
    public void destroy() throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceNotDestroyedFault    { 
        LOG.info("Executing operation destroy");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourcelifetime_1_2_draft_01_wsdl.ResourceNotDestroyedFault("ResourceNotDestroyedFault...");
    }

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.SubscriptionManager#getResourceProperty(javax.xml.namespace.QName  getResourcePropertyRequest )*
     */
    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName getResourcePropertyRequest) throws org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault , org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault    { 
        LOG.info("Executing operation getResourceProperty");
        System.out.println(getResourcePropertyRequest);
        try {
            org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01.GetResourcePropertyResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.ResourceUnknownFault("ResourceUnknownFault...");
        //throw new org.oasis_open.docs.wsrf._2004._06.wsrf_ws_resourceproperties_1_2_draft_01_wsdl.InvalidResourcePropertyQNameFault("InvalidResourcePropertyQNameFault...");
    }

    /* (non-Javadoc)
     * @see org.oasis_open.docs.wsn._2004._06.wsn_ws_basenotification_1_2_draft_01_wsdl.SubscriptionManager#pauseSubscription(*
     */
    public void pauseSubscription() throws ResourceUnknownFault , PauseFailedFault    { 
        LOG.info("Executing operation pauseSubscription");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ResourceUnknownFault("ResourceUnknownFault...");
        //throw new PauseFailedFault("PauseFailedFault...");
    }

}
