
package org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:24:42.419-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "AddRefusedFault", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.xsd")
public class AddRefusedFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.AddRefusedFaultType addRefusedFault;

    public AddRefusedFault() {
        super();
    }
    
    public AddRefusedFault(String message) {
        super(message);
    }
    
    public AddRefusedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AddRefusedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.AddRefusedFaultType addRefusedFault) {
        super(message);
        this.addRefusedFault = addRefusedFault;
    }

    public AddRefusedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.AddRefusedFaultType addRefusedFault, Throwable cause) {
        super(message, cause);
        this.addRefusedFault = addRefusedFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.AddRefusedFaultType getFaultInfo() {
        return this.addRefusedFault;
    }
}
