
package org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:24:42.410-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "ContentCreationFailedFault", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.xsd")
public class ContentCreationFailedFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.ContentCreationFailedFaultType contentCreationFailedFault;

    public ContentCreationFailedFault() {
        super();
    }
    
    public ContentCreationFailedFault(String message) {
        super(message);
    }
    
    public ContentCreationFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ContentCreationFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.ContentCreationFailedFaultType contentCreationFailedFault) {
        super(message);
        this.contentCreationFailedFault = contentCreationFailedFault;
    }

    public ContentCreationFailedFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.ContentCreationFailedFaultType contentCreationFailedFault, Throwable cause) {
        super(message, cause);
        this.contentCreationFailedFault = contentCreationFailedFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.ContentCreationFailedFaultType getFaultInfo() {
        return this.contentCreationFailedFault;
    }
}
