
package org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01_wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.3
 * 2013-04-11T11:24:42.402-04:00
 * Generated source version: 2.6.3
 */

@WebFault(name = "UnsupportedMemberInterfaceFault", targetNamespace = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.xsd")
public class UnsupportedMemberInterfaceFault extends Exception {
    
    private org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.UnsupportedMemberInterfaceFaultType unsupportedMemberInterfaceFault;

    public UnsupportedMemberInterfaceFault() {
        super();
    }
    
    public UnsupportedMemberInterfaceFault(String message) {
        super(message);
    }
    
    public UnsupportedMemberInterfaceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedMemberInterfaceFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.UnsupportedMemberInterfaceFaultType unsupportedMemberInterfaceFault) {
        super(message);
        this.unsupportedMemberInterfaceFault = unsupportedMemberInterfaceFault;
    }

    public UnsupportedMemberInterfaceFault(String message, org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.UnsupportedMemberInterfaceFaultType unsupportedMemberInterfaceFault, Throwable cause) {
        super(message, cause);
        this.unsupportedMemberInterfaceFault = unsupportedMemberInterfaceFault;
    }

    public org.oasis_open.docs.wsrf._2004._06.wsrf_ws_servicegroup_1_2_draft_01.UnsupportedMemberInterfaceFaultType getFaultInfo() {
        return this.unsupportedMemberInterfaceFault;
    }
}
